CREATE TABLE [dbo].[DimDate](
	[DateKey] [int] NOT NULL,
	[CalendarYear] [smallint] NOT NULL,
	[MonthOfYear] [tinyint] NOT NULL,

 CONSTRAINT [PK_dbo.DimDate] PRIMARY KEY CLUSTERED 
(
	[DateKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

